
import java.awt.Image;
import java.io.IOException;
import static java.util.Locale.filter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author pato
 */
public class SegundaVentana extends javax.swing.JFrame {

    /**
     * Creates new form SegundaVentana
     */
    
    Registro Registro = new Registro();
    private FileNameExtensionFilter filter=new FileNameExtensionFilter("Archivo",".jpg");
    public static String rutaimagen="";
    public void seteo() throws IOException{
        Registro.singUn();
        AquiNombre.setText(Registro.nombre);
        AquiCorreo.setText(Registro.correo1);
        AquiAño.setText(Registro.año);
        AquiEdad.setText(Registro.edad);
        
    }
    public SegundaVentana() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AquiCarrera = new javax.swing.JPanel();
        FOTO = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AquiNombre = new javax.swing.JLabel();
        AquiCorreo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AquiAño = new javax.swing.JLabel();
        AquiEdad = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaParaListaAmigos = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaParaGente = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        Correodeamigo = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("jLabel2");

        jLabel3.setText("Correo");

        jLabel4.setText("Carrera");

        jLabel5.setText("Año de carrera");

        jLabel6.setText("Edad");

        jLabel7.setText("Lista de amigos");

        AreaParaListaAmigos.setColumns(20);
        AreaParaListaAmigos.setRows(5);
        jScrollPane1.setViewportView(AreaParaListaAmigos);

        jLabel8.setText("Personas inscritas en la red social ");

        AreaParaGente.setColumns(20);
        AreaParaGente.setRows(5);
        jScrollPane2.setViewportView(AreaParaGente);

        jLabel10.setText("Buscar amigo por correo: ");

        Buscar.setText("Buscar");

        jButton1.setText("Foto de perfil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AquiCarreraLayout = new javax.swing.GroupLayout(AquiCarrera);
        AquiCarrera.setLayout(AquiCarreraLayout);
        AquiCarreraLayout.setHorizontalGroup(
            AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AquiCarreraLayout.createSequentialGroup()
                .addGroup(AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AquiCarreraLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(FOTO, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AquiCarreraLayout.createSequentialGroup()
                        .addGroup(AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AquiCarreraLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)
                                .addGap(38, 38, 38))
                            .addGroup(AquiCarreraLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(AquiCarreraLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(60, 60, 60)
                                        .addComponent(AquiNombre))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addGroup(AquiCarreraLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGroup(AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(AquiCarreraLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2))
                                            .addGroup(AquiCarreraLayout.createSequentialGroup()
                                                .addGap(68, 68, 68)
                                                .addGroup(AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(AquiCorreo)
                                                    .addComponent(AquiAño)
                                                    .addComponent(AquiEdad))))))))
                        .addGroup(AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AquiCarreraLayout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLabel7))
                            .addGroup(AquiCarreraLayout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AquiCarreraLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(151, 151, 151))
            .addGroup(AquiCarreraLayout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Correodeamigo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Buscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AquiCarreraLayout.setVerticalGroup(
            AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AquiCarreraLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(AquiCarreraLayout.createSequentialGroup()
                        .addComponent(FOTO, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(AquiNombre))
                        .addGap(18, 18, 18)
                        .addGroup(AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(AquiCorreo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(AquiAño))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(AquiEdad))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap(103, Short.MAX_VALUE))
                    .addGroup(AquiCarreraLayout.createSequentialGroup()
                        .addGroup(AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(14, 14, 14)
                        .addGroup(AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(24, 24, 24)
                        .addGroup(AquiCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Correodeamigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buscar))
                        .addGap(72, 72, 72))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AquiCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AquiCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser dlg= new JFileChooser();
        dlg.setFileFilter(filter);
        int opcion=dlg.showOpenDialog(this);
        if(opcion==JFileChooser.APPROVE_OPTION){
            String file = dlg.getSelectedFile().getPath();
            /**
            * toma la ruta de la imagen
            */
            rutaimagen=file;
            FOTO.setIcon(new ImageIcon(file));
            ImageIcon icono=new ImageIcon(file);
            Image logo = icono.getImage();
            Image newimagen=logo.getScaledInstance(175, 175, java.awt.Image.SCALE_SMOOTH);
            ImageIcon newicono =new ImageIcon(newimagen);
            FOTO.setIcon(newicono);
            FOTO.setSize(200,200);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegundaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegundaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegundaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegundaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SegundaVentana d = new SegundaVentana();
                try {
                    d.seteo();
                } catch (IOException ex) {
                    Logger.getLogger(SegundaVentana.class.getName()).log(Level.SEVERE, null, ex);
                }
                d.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AquiAño;
    private javax.swing.JPanel AquiCarrera;
    private javax.swing.JLabel AquiCorreo;
    private javax.swing.JLabel AquiEdad;
    private javax.swing.JLabel AquiNombre;
    private javax.swing.JTextArea AreaParaGente;
    private javax.swing.JTextArea AreaParaListaAmigos;
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField Correodeamigo;
    private javax.swing.JLabel FOTO;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
